### ISSUE TITLE
Wrong order of removing/adding recipes

### ISSUE THREAD

**Issue by winnetrie83** [Team-AbCiv/RailcraftTweaker#1]
If i remove a recipe from the rollingmachine and after that i add a new recipe for the removed item, the new recipe isn't added.
If i remove the "remove recipe line" from the script and keep the add new recipe line, a new recipe is added. So both code adding and removing works fine. So my conclusion is you run the add recipe code first and the remove recipe afterwards, wich is the wrong order.

example:
The following code does not add anything:

```
mods.railcraft.RollingMachine.remove(<railcraft:*>);
mods.railcraft.RollingMachine.addShaped("standardrail", <railcraft:rail:0>, [[null, <ore:ingotNickel>, <ore:ingotSteel>], [null, <ore:ingotNickel>, <ore:ingotSteel>], [null, <ore:ingotNickel>, <ore:ingotSteel>]]);

```

This code will add a new recipe:

`mods.railcraft.RollingMachine.addShaped("standardrail", <railcraft:rail:0>, [[null, <ore:ingotNickel>, <ore:ingotSteel>], [null, <ore:ingotNickel>, <ore:ingotSteel>], [null, <ore:ingotNickel>, <ore:ingotSteel>]]);
`

This will remove all railcraft recipes from the rollingmachine(i tested it):

`mods.railcraft.RollingMachine.remove(<railcraft:*>);
`

**Comment by winnetrie83** [comment]
Since there is no response, i have added the railcraft api to my mod and tried to achieve the same stuff. I have been succesfully this far. I can confirm putting the remove code before the adding code works as a charm. So all you have to do is switch the methods from position and your done. I would really appreciate it.

**Comment by 3TUSK** [comment]
![hyperthonk](https://discordemoji.com/assets/emoji/HyperThink.png)

*It took me about one minute to realize what I have done……*

Not sure when I can find some free time to fix this, but at least I know *how* to fix this now.

**Comment by CdRGit** [comment]
Would you by any chance have a compiled version with your fix?

**Comment by dudebehinddude** [comment]
bump

**Comment by 3TUSK** [comment]
Apologize for the long delay - many things happened in real life. 

The fix found in GH-2 is now merged, and a new update will be available as soon as possible.

**Comment by 3TUSK** [comment]
@DUDEbehindDUDE @CdRGit @winnetrie83 
The fix is now available as part of https://www.curseforge.com/minecraft/mc-mods/railcrafttweaker/files/3250350. Let me know any further issues by opening a new issue ticket.
