### ISSUE TITLE
Can't create small shaped Rolling Machine recipes

### ISSUE THREAD

**Issue by xJon** [Team-AbCiv/RailcraftTweaker#5]
E.g. one recipe that matches this default behaviour:
![image](https://github.com/Team-AbCiv/RailcraftTweaker/assets/8945347/0cf39956-3a07-48a8-97ba-d680bb6e4e8c)
![image](https://github.com/Team-AbCiv/RailcraftTweaker/assets/8945347/cec2e6d1-6783-4f41-8a46-c8d77d6a8595)

Using:
```
RollingMachine.addShaped("brass_plate", <railcraft:plate:11>,
							[[<railcraft:ingot:9>, <railcraft:ingot:9>],
							[<railcraft:ingot:9>, <railcraft:ingot:9>]]);
```
Does not work, and freezes the game:
`[Client thread/WARN]: Failed to identify mods.railcraft.common.util.crafting.RollingMachineCrafter$$Lambda$4764/653369188 (untransformed name: mods.railcraft.common.util.crafting.RollingMachineCrafter$$Lambda$4764.653369188)`

**Comment by 3TUSK** [comment]
Please try this new version https://www.curseforge.com/minecraft/mc-mods/railcrafttweaker/files/5294398 and see if it fixes the issue.

**Comment by xJon** [comment]
@3TUSK This works almost flawlessly, with the only issue being the JEI recipe preview, for this vertical recipe:
```
RollingMachine.addShaped("iron_electrode", <railcraft:charge:7>,
								[[<railcraft:plate:0>],
								[<railcraft:plate:0>],
								[<railcraft:plate:0>]]);
```
Looking like this:
![image](https://github.com/Team-AbCiv/RailcraftTweaker/assets/8945347/45bffc5e-0b0a-48b1-89a7-41f2eb00c5e5)

However in practice:
![image](https://github.com/Team-AbCiv/RailcraftTweaker/assets/8945347/4c166a6f-a371-4825-9330-acd73d77d0f3)
![image](https://github.com/Team-AbCiv/RailcraftTweaker/assets/8945347/b790c084-a2ef-4027-b72a-8fb0170ec6da)

**Comment by 3TUSK** [comment]
> with the only issue being the JEI recipe preview, for this vertical recipe

Quick investigation shows that this is Railcraft's issue. 

Not sure what I can do though. Fixing this one outside of Railcraft is tricky, and Railcraft mainline development is in hiatus.

**Comment by xJon** [comment]
Thank you for the response! Closing this as resolved.
